### ISSUE TITLE
Tech review tracklist

### ISSUE THREAD

**Issue by RobPasMue** [ansys/ansys-tools-local-product-launcher#130]
# Tech review

Hi @greschd @ludovicsteinbach - I have started having a look to the repository as part of the request to go public. I have differentiated between two gross sections: necessary tasks and nice-to-have ones. I will try to submit PRs for the list below, independently. And I will get started with the required ones. If you guys can help me out, that'd be great in any case. I will link the PRs in this issue as well.

PS: I might find more required/optional tasks - but in that case I will continue to submit them here.

## Required

- [x] Documentation build requires also PDF #136 
- [x] Add release stages and stable docs #131
- [x] Add smoke tests and wheelhouse action #131
- [x] Update start year of license (2022) in source code #132
- [x] Upload coverage results as an artifact #135  
- [x] Reorganize docs to have top bar showing main documentation sections: API reference, Getting started, User guide and Examples. Current CLI Reference, rational and creating launcher plugin sections could go under user guide  #133
- [x] Add breadcrumbs to doc  #139
- [x] Docs review completed (by @PipKat) on 2//8/23.

## Optional

- [x] Missing CONTRIBUTORS file, #138 
- [x] Update main Python version to 3.11/3.12 in workflow #134
- [x] ~~Propose using Ansys actions with poetry and tox @greschd~~ Skipping, because the ansys actions don't provide an option to go through `tox`.
- [x] ~~Upload coverage to codecov.io [to be done after publishing]~~ Keeping track in https://github.com/ansys-internal/ansys-tools-local-product-launcher/issues/130#issuecomment-1930004598
- [x] Adding examples #140
- [x] Updating badges and metadata #137
